### PR TITLE
Update_2 light-it-up.cpp

### PR DESCRIPTION
**Pull request by anmolgupta11**
//The code was giving an error on test case 5, i.e.
input
5 10
1 3 5 6 8
output
5
Answer
6

But after putting = sign in the statement a[i+1] - a[i] >= diff, code runs correctly on this test case but again fails for test case 6, i.e.

input
7 1000000000
1 10001 10011 20011 20021 40021 40031

output
999959999

Answer
999999969

Help find the problem in solving this test case.

### CODE REVIEW

**Comment by kantuni** [comment]
I'll take a look at the problem shortly.

**Comment by kantuni** [comment]
@anmolgupta11, it's solved now. 
Take a look at the [solution](https://github.com/kantuni/Codeforces/blob/master/1000B/light-it-up.cpp) and let me know if you need any help understanding it.

**Comment by kantuni** [comment]
Intuition behind the solution:
There are few scenarios that will give us the optimal answer:
1. no elements will be added
2. the added element will be of the form `a[i] - 1`
3. the added element will be of the form `a[i] + 1`

1 can be easily calculated in `O(n)`. To calculate 2 and 3 in `O(n)` one needs to keep prefix sums for odd and even index deltas `a[i] - a[i - 1]`.

**Comment by anmolgupta11** [comment]
Thank you!

**Pull request closed without merging**
